async (page) => {
  const checks = [], errors = [], failedRequests = [];
  const check = (name, passed, detail = null) => checks.push({ name, passed: Boolean(passed), detail });
  const originUrl = page.url();
  const root = originUrl.endsWith('/') ? originUrl : originUrl + '/';
  page.on('pageerror', error => errors.push(String(error)));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('requestfailed', request => failedRequests.push({ url: request.url(), error: request.failure()?.errorText }));
  page.on('response', response => { if (response.status() >= 400) failedRequests.push({ url: response.url(), status: response.status() }); });
  const response = await page.goto(root);
  check('Live game returns HTTP 200', response.status() === 200);
  await page.waitForFunction(() => window.oceanQA?.ready, { timeout: 30000 });
  await page.waitForTimeout(1500);
  check('WebGL2 initialized with finite state', await page.evaluate(() => oceanQA.diagnostics().webgl2 && oceanQA.diagnostics().finite));
  await page.getByRole('button', { name: 'Storm', exact: true }).click();
  check('Storm click changes sea, rain and clouds', await page.evaluate(() => { const s=oceanQA.state();return s.sea===.9&&s.rain&&s.clouds===.98; }));
  await page.getByRole('button', { name: /Below/ }).click();
  await page.waitForFunction(() => oceanQA.diagnostics().underwater, null, { timeout: 15000 });
  check('Below enters underwater', await page.evaluate(() => oceanQA.state().view==='underwater'&&oceanQA.diagnostics().underwater));
  await page.getByRole('button', { name: 'Night', exact: true }).click();
  check('Night preset updates lighting time', await page.evaluate(() => oceanQA.state().timeOfDay===0));
  await page.getByRole('button', { name: /Fly/ }).click();
  const before = await page.evaluate(() => oceanQA.diagnostics().camera);
  await page.keyboard.down('w'); await page.waitForTimeout(300); await page.keyboard.up('w');
  const after = await page.evaluate(() => oceanQA.diagnostics().camera);
  check('Free flight moves', before.some((v,i)=>Math.abs(v-after[i])>.01));
  await page.getByRole('button', { name: 'Open sea', exact: true }).click();
  await page.getByRole('button', { name: /Drift/ }).click();
  const resources = await page.evaluate(() => performance.getEntriesByType('resource').map(r=>r.name));
  check('Game assets load from the repository subpath', resources.some(url=>url.includes('/assets/')&&url.endsWith('.js')), resources.filter(url=>url.includes('/assets/')));
  const journeyResponse = await page.goto(root + 'journey/');
  check('Live journey returns HTTP 200', journeyResponse.status()===200);
  check('Journey has eight numbered sections', await page.locator('article h2').count()===8);
  await page.locator('#lesson-sea').fill('0.9');
  check('Interactive wave lesson responds', await page.locator('#lesson-value').textContent()==='90%');
  await page.getByRole('button',{name:'Animate the waves',exact:true}).click();
  check('Wave lesson animation toggles', await page.getByRole('button',{name:'Pause the waves',exact:true}).getAttribute('aria-pressed')==='true');
  await page.getByRole('button',{name:'Pause the waves',exact:true}).click();
  for (const img of await page.locator('article img').all()) { await img.scrollIntoViewIfNeeded(); await img.evaluate(i=>i.decode()); }
  check('Journey screenshots loaded', await page.locator('article img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0)));
  await page.setViewportSize({width:390,height:844});
  check('Mobile journey has no document overflow', await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.getByRole('link',{name:'Play the ocean ↗',exact:true}).click();
  await page.waitForFunction(()=>window.oceanQA?.ready);
  check('Journey Play link opens the game', page.url()===root);
  check('No browser errors', errors.length===0, errors);
  check('No failed assets or HTTP errors', failedRequests.length===0, failedRequests);
  return { checkedAt:new Date().toISOString(),root,passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed),checks,errors,failedRequests };
}
