// Playwright CLI run-code function; open /learn/ before running.
async (page) => {
  const root=page.url().split('#')[0].split('?')[0];
  const checks=[],errors=[],failedRequests=[];
  const check=(name,passed,detail=null)=>checks.push({name,passed:Boolean(passed),detail});
  page.on('pageerror',error=>errors.push(String(error)));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  page.on('requestfailed',request=>failedRequests.push({url:request.url(),error:request.failure()?.errorText}));
  page.on('response',response=>{if(response.status()>=400)failedRequests.push({url:response.url(),status:response.status()});});
  await page.setViewportSize({width:1440,height:1000});
  const response=await page.goto(root);
  await page.waitForFunction(()=>document.querySelector('#wave-sum')?.getAttribute('d'));
  check('Guide returns HTTP 200',response.status()===200);
  check('One main heading and eight navigable sections',await page.locator('h1').count()===1&&await page.locator('article>section[id]').count()===8);
  check('Seven actual source excerpts are rendered',await page.locator('[data-snippet]').count()===7);
  check('Every internal section link resolves',await page.locator('a[href^="#"]').evaluateAll(links=>links.every(a=>document.getElementById(a.hash.slice(1)))));
  check('Source excerpt links identify files and line ranges',await page.locator('.code-example figcaption a').evaluateAll(links=>links.every(a=>a.href.includes('/blob/')&&/\/src\/\w+\.js#L\d+-L\d+$/.test(a.href))));
  await page.screenshot({path:'output/guide-desktop.png'});
  await page.locator('#waves').scrollIntoViewIfNeeded();
  const baseline=await page.locator('#wave-sum').getAttribute('d');
  await page.waitForTimeout(120);
  check('Wave lesson is still by default',baseline===await page.locator('#wave-sum').getAttribute('d')&&await page.locator('#lab-play').getAttribute('aria-pressed')==='false');
  await page.locator('#lab-sea').fill('0.9');
  check('Sea state changes shape and its text readout',baseline!==await page.locator('#wave-sum').getAttribute('d')&&(await page.locator('#lab-sea-value').textContent())==='90%');
  const layered=await page.locator('#wave-sum').getAttribute('d');
  await page.locator('#lab-layers').uncheck();
  check('Layer switch changes the sum and description',layered!==await page.locator('#wave-sum').getAttribute('d')&&(await page.locator('#wave-readout').textContent()).includes('One wave'));
  await page.locator('#lab-normals').uncheck();
  check('Surface-direction switch removes arrows',await page.locator('#normal-arrows path').count()===0);
  const still=await page.locator('#wave-sum').getAttribute('d');
  await page.getByRole('button',{name:'Step once',exact:true}).click();
  check('Step produces a new still frame',still!==await page.locator('#wave-sum').getAttribute('d')&&await page.locator('#lab-play').getAttribute('aria-pressed')==='false');
  await page.getByRole('button',{name:'Animate waves',exact:true}).click();
  await page.waitForTimeout(150);
  check('Explicit animation starts',await page.locator('#lab-play').getAttribute('aria-pressed')==='true');
  await page.getByRole('button',{name:'Pause waves',exact:true}).click();
  const paused=await page.locator('#wave-sum').getAttribute('d');await page.waitForTimeout(120);
  check('Pause stops animation',paused===await page.locator('#wave-sum').getAttribute('d'));
  await page.getByRole('button',{name:'Reset lesson',exact:true}).click();
  check('Reset restores defaults and normal arrows',await page.locator('#lab-sea').inputValue()==='0.43'&&await page.locator('#lab-layers').isChecked()&&await page.locator('#normal-arrows path').count()>0&&baseline===await page.locator('#wave-sum').getAttribute('d'));
  await page.locator('#lab-sea').focus();await page.keyboard.press('ArrowRight');
  check('Keyboard changes the sea slider',await page.locator('#lab-sea').inputValue()==='0.44');
  await page.locator('#view-angle').fill('0');
  check('Straight-on reflection is about two percent',(await page.locator('#reflection-readout').textContent()).startsWith('2.0%'));
  await page.locator('#view-angle').fill('85');
  check('Grazing reflection rises above sixty percent',await page.locator('#reflection-fill').evaluate(el=>parseFloat(el.style.width)>60));
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForFunction(()=>document.querySelector('#lab-play').disabled,null,{timeout:2000});
  check('Reduced motion disables continuous animation',await page.locator('#lab-play').isDisabled());
  await page.getByRole('button',{name:'Step once',exact:true}).click();
  check('Reduced motion retains manual stepping',Number(await page.locator('#wave-plot').getAttribute('data-time'))>0);
  await page.emulateMedia({reducedMotion:'no-preference'});
  await page.waitForFunction(()=>!document.querySelector('#lab-play').disabled,null,{timeout:2000});
  check('Motion preference can be changed without reloading',await page.locator('#lab-play').isEnabled());
  for(const [width,height] of [[390,844],[320,568],[844,390]]){
    await page.setViewportSize({width,height});await page.reload();await page.waitForFunction(()=>document.querySelector('#wave-sum')?.getAttribute('d'));
    await page.locator('#waves').scrollIntoViewIfNeeded();
    check(`${width}x${height}: no page-wide overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    check(`${width}x${height}: mobile contents initially collapsed`,await page.locator('.toc').evaluate(el=>!el.open));
    await page.locator('.toc summary').click();await page.getByRole('link',{name:'03 · Equations into waves',exact:true}).click();
    check(`${width}x${height}: contents link navigates`,page.url().endsWith('#waves'));
    await page.locator('#lab-sea').fill('0.65');await page.locator('#lab-normals').uncheck();
    check(`${width}x${height}: lesson controls respond`,(await page.locator('#lab-sea-value').textContent())==='65%'&&await page.locator('#normal-arrows path').count()===0);
    check(`${width}x${height}: primary touch targets are 44px high`,await page.locator('.lab-actions button, input[type=range], .checks label').evaluateAll(nodes=>nodes.every(n=>n.getBoundingClientRect().height>=44)));
  }
  await page.setViewportSize({width:390,height:844});await page.goto(root);await page.waitForFunction(()=>document.querySelector('#wave-sum')?.getAttribute('d'));
  await page.screenshot({path:'output/guide-mobile.png'});
  await page.locator('.lab').scrollIntoViewIfNeeded();await page.screenshot({path:'output/guide-mobile-lesson.png'});
  await page.setViewportSize({width:1440,height:1000});await page.locator('.lab').scrollIntoViewIfNeeded();await page.screenshot({path:'output/guide-desktop-lesson.png'});
  for(const img of await page.locator('main img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(el=>el.decode());}
  check('All actual-render images decode',await page.locator('main img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0)));
  await page.locator('details.deep').first().locator('summary').click();
  check('Optional code details expand',await page.locator('details.deep').first().evaluate(el=>el.open));
  check('Legal-notices link returns 200',await page.evaluate(async()=>{const response=await fetch(document.querySelector('a[href$="THIRD_PARTY_NOTICES.txt"]').href);return response.status===200;}));
  // Test the text-first fallback in a separate context with scripts disabled.
  const context=await page.context().browser().newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
  const plain=await context.newPage();await plain.goto(root);
  check('Guide text and source excerpts work without JavaScript',await plain.locator('h1').isVisible()&&await plain.locator('[data-snippet]').count()===7&&(await plain.locator('body').textContent()).includes('The interactive lesson needs JavaScript'));
  await context.close();
  await page.getByRole('link',{name:'The journey',exact:true}).click();
  check('Journey link opens the existing learning page',page.url().includes('/journey/')&&await page.locator('article h2').count()===8);
  const guideBack=page.getByRole('link',{name:'How code becomes ocean',exact:true});
  check('Journey has the canonical guide link',(await guideBack.getAttribute('href'))==='https://az9713.github.io/gpt-6-astra-3D-ocean/learn/');
  if(root.startsWith('https://'))await guideBack.click();else await page.goto(root);
  await page.waitForFunction(()=>document.querySelector('#wave-sum')?.getAttribute('d'));
  check('Journey links back to the field guide',page.url().endsWith('/learn/'));
  await page.getByRole('link',{name:'Play the ocean',exact:false}).first().click();
  await page.waitForFunction(()=>window.oceanQA?.ready);
  check('Guide Play link opens a finite WebGL ocean',await page.evaluate(()=>oceanQA.diagnostics().finite&&oceanQA.diagnostics().webgl2));
  check('No browser errors',errors.length===0,errors);
  check('No failed requests or HTTP errors',failedRequests.length===0,failedRequests);
  return {checkedAt:new Date().toISOString(),root,provenance:'Desktop Chrome with emulated viewports and reduced-motion preference; not physical-device testing.',passed:checks.filter(c=>c.passed).length,failed:checks.filter(c=>!c.passed),checks};
}
